LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Controllers/PhanQuyenController.cs
using LinhDGT_Electronic.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace LinhDGT_Electronic.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PhanQuyenController : Controller
    {
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Admin/PhanQuyen
        public ActionResult Index()
        {
            var item = _dbContext.Roles.ToList();
            return View(item);
        }

        public ActionResult ThemQuyenHan()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemQuyenHan(IdentityRole model)
        {
            if (ModelState.IsValid)
            {
                var phanquyen = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_dbContext));
                phanquyen.Create(model);

                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult SuaQuyenHan(string id)
        {
            var item = _dbContext.Roles.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaQuyenHan(IdentityRole model)
        {
            if (ModelState.IsValid)
            {
                var phanquyen = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_dbContext));
                phanquyen.Update(model);

                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult XoaQuyenHan(string id)
        {
            var item = _dbContext.Roles.Find(id);

            if (item != null)
            {
                _dbContext.Roles.Remove(item);
                _dbContext.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/PhanQuyen/Index.cshtml
@using Microsoft.AspNet.Identity.EntityFramework
@model IEnumerable<IdentityRole>
@{
    ViewBag.Title = "Phân quyền người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Danh sách quyền hạn</div>
        <a class="button-admin-control-create" href="/admin/phanquyen/themquyenhan" style="margin-right:16px">Thêm mới</a>
    </div>
    <div class="body-content-admin">
        <div class="table-content">

            <table class="table-body">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Quyền hạn</th>
                        <th colspan="2" style="width:100px">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {
                            <tr id="row_quyenhan_@item.Id">
                                <td>@i</td>
                                <td>@item.Name</td>
                                <td><a class="button-admin-control-edit" href="/admin/phanquyen/suaquyenhan/@item.Id"><i class="fa fa-pen"></i> </a></td>
                                <td><a class="button-admin-control-edit button-delete-quyenhan-by-id" style="background-color:red" href="" data-id="@item.Id"><i class="fa fa-trash"></i> </a></td>
                            </tr>
                            i++;
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="7">Không có bản ghi</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="body-footer">

    </div>
</div>


<script>
    $(document).ready(function () {
        $('body').on('click', '.button-delete-quyenhan-by-id', function () {
            var id = $(this).data("id");
            var conf = confirm('Xoá bản ghi?');
            if (conf === true) {
                $.ajax({
                    url: '/admin/phanquyen/xoaquyenhan',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            $('#row_quyenhan_' + id).remove();
                            location.reload();
                            alert('Đã xoá!');
                        }
                    }
                });
            }
        });

    });
</script>

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/PhanQuyen/SuaQuyenHan.cshtml
@using Microsoft.AspNet.Identity.EntityFramework
@model IdentityRole
@{
    ViewBag.Title = "Sửa quyền hạn";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";


}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Sửa quyền hạn</div>
    </div>
    <div class="body-content-admin">
        @using (Html.BeginForm("ThemQuyenHan", "PhanQuyen", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(x=>x.Id)
            <div class="form-mode">
                <div class="item">
                    <label for="">Tên quyền hạn</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "input", @placeholder = "Nhập tên quyền hạn...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.Name, null, new { @style = "color:red" })
                </div>
                <div class="item" style="justify-content: end; column-gap: 16px;">
                    <a href="/admin/phanquyen/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
                    <button class="button-pop-up-footer" type="submit">Xác nhận</button>
                </div>
            </div>
        }
    </div>
    <div class="body-footer">

    </div>
</div>
@*<script>
        $(document).ready(function () {
            $('body').on('click', '.button-delete-danhmuc-by-id', function () {
                var id = $(this).data("id");
                var conf = confirm('Xoá bản ghi?');
                if (conf === true) {
                    $.ajax({
                        url: '/admin/danhmuc/xoadanhmuc',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#row_danhmuc_' + id).remove();
                                location.reload();
                                alert('Đã xoá!');
                            }
                        }
                    });
                }
            });

        });
    </script>*@

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/PhanQuyen/ThemQuyenHan.cshtml
@using Microsoft.AspNet.Identity.EntityFramework
@model IdentityRole
@{
    ViewBag.Title = "Thêm quyền hạn";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";


}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Thêm mới quyền hạn</div>
    </div>
    <div class="body-content-admin">
        @using (Html.BeginForm("ThemQuyenHan", "PhanQuyen", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-mode">
                <div class="item">
                    <label for="">Tên quyền hạn</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "input", @placeholder = "Nhập tên quyền hạn...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.Name, null, new { @style = "color:red" })
                </div>
                <div class="item" style="justify-content: end; column-gap: 16px;">
                    <a href="/admin/phanquyen/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
                    <button class="button-pop-up-footer" type="submit">Xác nhận</button>
                </div>
            </div>
        }
    </div>
    <div class="body-footer">

    </div>
</div>
@*<script>
        $(document).ready(function () {
            $('body').on('click', '.button-delete-danhmuc-by-id', function () {
                var id = $(this).data("id");
                var conf = confirm('Xoá bản ghi?');
                if (conf === true) {
                    $.ajax({
                        url: '/admin/danhmuc/xoadanhmuc',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#row_danhmuc_' + id).remove();
                                location.reload();
                                alert('Đã xoá!');
                            }
                        }
                    });
                }
            });

        });
    </script>*@