LinhDGT_Electronic/LinhDGT_Electronic/Models/EF/SanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinhDGT_Electronic.Models.EF
{
    [Table("sanpham")]
    public class SanPham
    {
        public SanPham() {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SanPhamID { get; set; }
        [Required(ErrorMessage = "Tên sản phẩm không được rỗng!")]
        public string SanPhamName { get; set; }

        [Required(ErrorMessage ="Ảnh đại diện là trường bắt buộc!")]
        public string SanPhamImage { get; set; }
        [Required(ErrorMessage = "Năm sản xuất không được rỗng!")]
        public int SanPhamProducedYear { get; set; }

        [AllowHtml]
        public string SanPhamDescription { get; set; }
        public int DanhMucID { get; set; }
        public int ThuongHieuID { get; set; }
        [Required(ErrorMessage = "Số lượng không được rỗng!")]
        public int SanPhamQuantity { get; set; }
        public int SanPhamSellQuantity { get; set; }
        [Required(ErrorMessage = "Đơn giá không được rỗng!")]
        public double SanPhamUnitPrice { get; set; }
        public int SanPhamStatus { get; set; }
        public virtual DanhMuc DanhMuc { get; set;}
        public virtual ThuongHieu ThuongHieu { get; set;}
        public virtual ICollection<AnhSanPham> AnhSanPhams { get;set; }

        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get;set; }

        public int TruSoluong(int truSoluong)
        {
            return SanPhamQuantity - truSoluong;
        }
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Controllers/SanPhamController.cs
using LinhDGT_Electronic.Models.EF;
using LinhDGT_Electronic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace LinhDGT_Electronic.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SanPhamController : Controller
    {
        // GET: Admin/SanPham
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Admin/SanPham
        public ActionResult Index(int? page, string timkiem, string boloc, string sapxep)
        {
            ViewBag.sapxep = sapxep;
            ViewBag.sapxeptheoten = String.IsNullOrEmpty(sapxep) ? "ten_desc" : "";
            ViewBag.sapxeptheogia = sapxep == "gia" ? "gia_desc" : "gia";
            ViewBag.sapxeptheonamsanxuat = sapxep == "namsx" ? "namsx_desc" : "namsx";
            ViewBag.sapxeptheosoluong = sapxep == "soluong" ? "soluong_desc" : "soluong";
            IEnumerable<SanPham> items = _dbContext.SanPhams.OrderByDescending(x => x.SanPhamID);
            var pagesize = 10;
            if (timkiem != null)
            {
                page = 1;
            }
            else
            {
                timkiem = boloc;
            }
            ViewBag.boloc = boloc;
            
            switch (sapxep)
            {
                case "ten_desc":
                    items = items.OrderByDescending(p => p.SanPhamName);
                    break;
                case "gia":
                    items = items.OrderBy(p => p.SanPhamUnitPrice);
                    break;
                case "gia_desc":
                    items = items.OrderByDescending(p => p.SanPhamUnitPrice);
                    break;
                case "namsx":
                    items = items.OrderBy(p => p.SanPhamProducedYear);
                    break;
                case "namsx_desc":
                    items = items.OrderByDescending(p => p.SanPhamProducedYear);
                    break;
                case "soluong":
                    items = items.OrderBy(p => p.SanPhamQuantity);
                    break;
                case "soluong_desc":
                    items = items.OrderByDescending(p => p.SanPhamQuantity);
                    break;
                default:
                    items = items.OrderBy(p => p.SanPhamName);
                    break;
            }
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(timkiem))
            {
                items = items.Where(x => x.SanPhamName.ToLower().Contains(timkiem));
            }
            ViewBag.page = page;
            ViewBag.pagesize = pagesize;
            var pagenumber = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pagenumber, pagesize);
            return View(items);
        }
        [HttpGet]
        public ActionResult ThemSanPham()
        {
            ViewBag.DanhMucID = new SelectList(_dbContext.DanhMucs, "DanhMucID", "DanhMucName");
            ViewBag.ThuongHieuID = new SelectList(_dbContext.ThuongHieus, "ThuongHieuID", "ThuongHieuName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ThemSanPham(FormCollection frm, SanPham model, List<string> Images)
        {

            if (ModelState.IsValid)
            {
                model.SanPhamImage = "";
                var f = Request.Files["SanPhamImage"];
                if (f != null && f.ContentLength > 0)
                {
                    string filename = System.IO.Path.GetFileName(f.FileName);
                    string upath = Server.MapPath("~/Content/assets/images/" + filename);
                    f.SaveAs(upath);
                    model.SanPhamImage = filename;
                }
                if (Images != null && Images.Count > 0)
                {
                    for (int i = 0; i < Images.Count; i++)
                    {
                        
                           
                            model.AnhSanPhams.Add(new AnhSanPham
                            {
                                SanPhamID = model.SanPhamID,
                                AnhName = Images[i],
                                AnhStatus = true,
                            });
    
                    }
                }
                if (frm["status"] == "Kích hoạt")
                    model.SanPhamStatus = 1;
                else
                    model.SanPhamStatus = 2;
                _dbContext.SanPhams.Add(model);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DanhMucID = new SelectList(_dbContext.DanhMucs, "DanhMucID", "DanhMucName", model.DanhMucID);
            ViewBag.ThuongHieuID = new SelectList(_dbContext.ThuongHieus, "ThuongHieuID", "ThuongHieuName", model.ThuongHieuID);
            return View(model);
        }

        [HttpGet]
        public ActionResult SuaSanPham(int? id)
        {
            ViewBag.DanhMucID = new SelectList(_dbContext.DanhMucs, "DanhMucID", "DanhMucName");
            ViewBag.ThuongHieuID = new SelectList(_dbContext.ThuongHieus, "ThuongHieuID", "ThuongHieuName");
            var item = _dbContext.SanPhams.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SuaSanPham(FormCollection frm, SanPham model)
        {

            if (ModelState.IsValid)
            {
                model.SanPhamImage = "";
                var f = Request.Files["SanPhamImage"];
                if (f != null && f.ContentLength > 0)
                {
                    string filename = System.IO.Path.GetFileName(f.FileName);
                    string upath = Server.MapPath("~/Content/assets/images/" + filename);
                    f.SaveAs(upath);
                    model.SanPhamImage = filename;
                }
                if (frm["status"] == "Kích hoạt")
                    model.SanPhamStatus = 1;
                else model.SanPhamStatus = 2;
                _dbContext.SanPhams.Attach(model);
                _dbContext.Entry(model).Property(x => x.SanPhamName).IsModified = true;
                _dbContext.Entry(model).Property(x => x.SanPhamImage).IsModified = true;
                _dbContext.Entry(model).Property(x => x.SanPhamProducedYear).IsModified = true;
                _dbContext.Entry(model).Property(x => x.DanhMucID).IsModified = true;
                _dbContext.Entry(model).Property(x => x.ThuongHieuID).IsModified = true;
                _dbContext.Entry(model).Property(x => x.SanPhamQuantity).IsModified = true;
                _dbContext.Entry(model).Property(x => x.SanPhamUnitPrice).IsModified = true;
                _dbContext.Entry(model).Property(x => x.SanPhamStatus).IsModified = true;
                _dbContext.Entry(model).Property(x => x.SanPhamDescription).IsModified = true;
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DanhMucID = new SelectList(_dbContext.DanhMucs, "DanhMucID", "DanhMucName", model.DanhMucID);
            ViewBag.ThuongHieuID = new SelectList(_dbContext.ThuongHieus, "ThuongHieuID", "ThuongHieuName", model.ThuongHieuID);
            return View(model);
        }

        [HttpPost]
        public ActionResult XoaSanPham(int id)
        {
            var item = _dbContext.SanPhams.Find(id);
            if (item != null)
            {
                _dbContext.SanPhams.Remove(item);
                _dbContext.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        public ActionResult XoaTatCa(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var obj = _dbContext.SanPhams.Find(Convert.ToInt32(item));
                        _dbContext.SanPhams.Remove(obj);
                        _dbContext.SaveChanges();
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Controllers/SanPhamController.cs
using LinhDGT_Electronic.Models;
using LinhDGT_Electronic.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinhDGT_Electronic.Controllers
{
    public class SanPhamController : Controller
    {
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SanPhamTheoDanhMuc(int? page, string timkiem, string boloc, string sapxep, int danhmucid)
        {
            ViewBag.sapxep = sapxep;
            ViewBag.sapxeptheoten = String.IsNullOrEmpty(sapxep) ? "ten_desc" : "";
            ViewBag.sapxeptheogia = sapxep == "gia" ? "gia_desc" : "gia";
            ViewBag.sapxeptheonamsanxuat = sapxep == "namsx" ? "namsx_desc" : "namsx";
            ViewBag.sapxeptheosoluong = sapxep == "soluong" ? "soluong_desc" : "soluong";
            ViewBag.sapxeptheongaytao = sapxep == "ngaytao" ? "ngaytao_desc" : "ngaytao";
            IEnumerable<SanPham> items = _dbContext.SanPhams.Where(x => x.DanhMucID == danhmucid && x.SanPhamStatus == 1).OrderByDescending(x => x.SanPhamID);
            var pagesize = 10;
            if (timkiem != null)
            {
                page = 1;
            }
            else
            {
                timkiem = boloc;
            }
            ViewBag.boloc = boloc;
            switch (sapxep)
            {
                case "ten_desc":
                    items = items.OrderByDescending(p => p.SanPhamName);
                    break;
                case "gia":
                    items = items.OrderBy(p => p.SanPhamUnitPrice);
                    break;
                case "gia_desc":
                    items = items.OrderByDescending(p => p.SanPhamUnitPrice);
                    break;
                case "namsx":
                    items = items.OrderBy(p => p.SanPhamProducedYear);
                    break;
                case "namsx_desc":
                    items = items.OrderByDescending(p => p.SanPhamProducedYear);
                    break;
                case "soluong":
                    items = items.OrderBy(p => p.SanPhamQuantity);
                    break;
                case "soluong_desc":
                    items = items.OrderByDescending(p => p.SanPhamQuantity);
                    break;
                case "ngaytao":
                    items = items.OrderBy(p => p.SanPhamID);
                    break;
                case "ngaytao_desc":
                    items = items.OrderByDescending(p => p.SanPhamID);
                    break;
                default:
                    items = items.OrderBy(p => p.SanPhamName);
                    break;
            }
            ViewBag.name = _dbContext.DanhMucs.Where(x => x.DanhMucID == danhmucid).FirstOrDefault().DanhMucName;
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(timkiem))
            {
                items = items.Where(x => x.SanPhamName.ToLower().Contains(timkiem));
            }
            var pagenumber = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pagenumber, pagesize);
            return View(items);
        }
        public ActionResult SanPhamTheoThuongHieu(int? page, string timkiem, string boloc, string sapxep, int thuonghieuid)
        {
            ViewBag.sapxep = sapxep;
            ViewBag.sapxeptheoten = String.IsNullOrEmpty(sapxep) ? "ten_desc" : "";
            ViewBag.sapxeptheogia = sapxep == "gia" ? "gia_desc" : "gia";
            ViewBag.sapxeptheonamsanxuat = sapxep == "namsx" ? "namsx_desc" : "namsx";
            ViewBag.sapxeptheosoluong = sapxep == "soluong" ? "soluong_desc" : "soluong";
            ViewBag.sapxeptheongaytao = sapxep == "ngaytao" ? "ngaytao_desc" : "ngaytao";
            IEnumerable<SanPham> items = _dbContext.SanPhams.Where(x => x.ThuongHieuID == thuonghieuid && x.SanPhamStatus == 1).OrderByDescending(x => x.SanPhamID);
            var pagesize = 10;
            if (timkiem != null)
            {
                page = 1;
            }
            else
            {
                timkiem = boloc;
            }
            ViewBag.boloc = boloc;
            switch (sapxep)
            {
                case "ten_desc":
                    items = items.OrderByDescending(p => p.SanPhamName);
                    break;
                case "gia":
                    items = items.OrderBy(p => p.SanPhamUnitPrice);
                    break;
                case "gia_desc":
                    items = items.OrderByDescending(p => p.SanPhamUnitPrice);
                    break;
                case "namsx":
                    items = items.OrderBy(p => p.SanPhamProducedYear);
                    break;
                case "namsx_desc":
                    items = items.OrderByDescending(p => p.SanPhamProducedYear);
                    break;
                case "soluong":
                    items = items.OrderBy(p => p.SanPhamQuantity);
                    break;
                case "soluong_desc":
                    items = items.OrderByDescending(p => p.SanPhamQuantity);
                    break;
                case "ngaytao":
                    items = items.OrderBy(p => p.SanPhamID);
                    break;
                case "ngaytao_desc":
                    items = items.OrderByDescending(p => p.SanPhamID);
                    break;
                default:
                    items = items.OrderBy(p => p.SanPhamName);
                    break;
            }
            ViewBag.name = _dbContext.ThuongHieus.Where(x => x.ThuongHieuID == thuonghieuid).FirstOrDefault().ThuongHieuName;
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(timkiem))
            {
                items = items.Where(x => x.SanPhamName.ToLower().Contains(timkiem));
            }
            var pagenumber = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pagenumber, pagesize);
            return View(items);
        }
        public ActionResult ChiTietSanPham(int sanphamid)
        {
            var item = _dbContext.SanPhams.Where(x => x.SanPhamID == sanphamid).FirstOrDefault(x => x.SanPhamStatus == 1);
            return PartialView(item);
        }
        public ActionResult ChiTietSanPhamTheoDanhMuc(int danhmucid, int sanphamid)
        {
            ViewBag.danhmuc = _dbContext.DanhMucs.FirstOrDefault(x => x.DanhMucID == danhmucid).DanhMucName;
            var item = _dbContext.SanPhams.Where(x => x.SanPhamID == sanphamid && x.DanhMuc.DanhMucID == danhmucid).FirstOrDefault();
            return PartialView(item);
        }
        public ActionResult ChiTietSanPhamTheoThuongHieu(int thuonghieuid, int sanphamid)
        {
            ViewBag.thuonghieu = _dbContext.ThuongHieus.FirstOrDefault(x => x.ThuongHieuID == thuonghieuid).ThuongHieuName;
            var item = _dbContext.SanPhams.Where(x => x.SanPhamID == sanphamid && x.ThuongHieu.ThuongHieuID == thuonghieuid).FirstOrDefault();
            return PartialView(item);
        }

    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/SanPham/Index.cshtml
@model PagedList.PagedList<LinhDGT_Electronic.Models.EF.SanPham>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@*<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">*@
<div class="body">
    <div class="body-title-admin">
        <div class="title">Danh sách sản phẩm</div>
        @using (Html.BeginForm())
        {
            <div class="page-search">
                @Html.TextBox("timkiem", ViewBag.boloc as string, new { @class = "input-search", @placeholder = "Nhập từ khoá để tìm kiếm" })
                <input type="submit" class="button-search" value="Tìm kiếm" />
            </div>
         }
            <a class="button-admin-control-create" href="/admin/SanPham/themSanPham">Thêm mới</a>
            <a class="button-admin-control-delete" id="button-delete-all" style="display:flex;justify-content:center;align-items:center"><i class="fa-solid fa-trash"></i></a>
        </div>
    <div class="body-content-admin">
        <div class="table-content">
            <table class="table-body">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="SelectAll"></th>
                        <th>STT</th>
                        <th style="width: 200px;"> @Html.ActionLink("Tên sản phẩm", "Index", new { sapxep = ViewBag.sapxeptheoten, boloc = ViewBag.boloc })</th>
                        <th>Ảnh đại diện</th>
                        <th> @Html.ActionLink("Năm sản xuất", "Index", new { sapxep = ViewBag.sapxeptheonamsanxuat, boloc = ViewBag.boloc })</th>
                        <th>Danh mục</th>
                        <th>Thương hiệu</th>
                        <th> @Html.ActionLink("Số lượng", "Index", new { sapxep = ViewBag.sapxeptheosoluong, boloc = ViewBag.boloc })</th>
                        <th> @Html.ActionLink("Đơn giá", "Index", new { sapxep = ViewBag.sapxeptheogia, boloc = ViewBag.boloc })</th>
                        <th>Trạng thái</th>
                        <th colspan="2">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.page - 1) * ViewBag.pagesize + 1);
                        var status = "";

                        foreach (var item in Model)
                        {
                            if (item.SanPhamStatus == 1)
                            {
                                status = "Kích hoạt";
                            }
                            else if (item.SanPhamStatus == 2)
                            {
                                status = "Vô hiệu";
                            }
                            <tr id="row_sanpham_@item.SanPhamID">
                                <td><input type="checkbox" value="@item.SanPhamID"></td>
                                <td>@i</td>
                                <td><span style="width:200px;white-space:normal;text-overflow:ellipsis;">@item.SanPhamName</span></td>
                                <td><img src="~/Content/assets/images/@item.SanPhamImage" width="120" class="imgproduct" data-id="@item.SanPhamID" /></td>
                                <td>@item.SanPhamProducedYear</td>
                                <td>@item.DanhMuc.DanhMucName</td>
                                <td>@item.ThuongHieu.ThuongHieuName</td>
                                <td>@item.SanPhamQuantity.ToString("0,0")</td>
                                <td>@item.SanPhamUnitPrice.ToString("0,0 VNĐ")</td>
                                <td>@status</td>
                                <td style="display:flex; justify-content:center;border:unset"><a class="button-admin-control-edit" href="/admin/sanpham/suasanpham/@item.SanPhamID"><i class="fa-solid fa-pen"></i></a></td>
                                <td style="display:flex; justify-content:center;border:unset"><a data-id="@item.SanPhamID" class="button-admin-control-edit button-delete-sanpham-by-id" style="background-color:red;border-color:red"><i class="fa-solid fa-trash"></i></a></td>
                                <td style="display:flex; justify-content:center;border:unset"><a class="button-admin-control-edit" href="/admin/anhsanpham/index/@item.SanPhamID"><i class="fa-solid fa-image"></i></a></td>
                            </tr>
                            i++;
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="12">Không có bản ghi</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="body-footer">
        <div style="padding-left:16px;box-sizing:border-box">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sapxep = ViewBag.sapxep, boloc = ViewBag.boloc }))</div>
        <span style="padding-right: 16px;box-sizing:border-box">Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</span>
    </div>

</div>
@*<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>*@
<script>
    $(document).ready(function () {
        $('body').on('click', '#button-delete-all', function (e) {
            e.preventDefault();
            var str = "";
            var checkbox = $(this).parents('.body').find('tr td input:checkbox');
            var i = 0;

            checkbox.each(function () {
                if (this.checked) {
                    checkbox.attr('selected', 'checked');
                    var _id = $(this).val();
                    if (i === 0) {
                        str += _id;
                    }
                    else {
                        str += "," + _id;
                    }
                    i++;
                } else {
                    checkbox.attr('selected', '');

                }
            });
            if (str.length > 0) {
                var conf = confirm("Xoá các bản ghi đã chọn?");
                if (conf === true) {
                    $.ajax({
                        url: '/admin/sanpham/XoaTatCa',
                        type: 'POST',
                        data: { ids: str },
                        success: function (rs) {
                            if (rs.success) {
                                location.reload();
                            }
                        }
                    });
                }
            }
        });
        $('body').on('change', '#SelectAll', function () {

            var checkedStatus = this.checked;
            //alert(checkedStatus);
            var checkbox = $(this).parents('.table-body').find('tr td input:checkbox');
            checkbox.each(function () {
                this.checked = checkedStatus;
                if (this.checked) {
                    checkbox.attr('selected', 'checked');
                } else {
                    checkbox.attr('selected', '');
                }
            });
        });
        $('body').on('click', '.button-delete-sanpham-by-id', function () {
            var id = $(this).data("id");
            var conf = confirm('Xoá bản ghi?');
            if (conf === true) {
                $.ajax({
                    url: '/admin/sanpham/xoasanpham',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            $('#row_sanpham_' + id).remove();
                            location.reload();
                            alert('Đã xoá!');
                        }

                    }
                });
            }
        });
    });
</script>

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/SanPham/SuaSanPham.cshtml
@model LinhDGT_Electronic.Models.EF.SanPham
@{
    ViewBag.Title = "Sửa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="body" style="overflow:auto">
    @using (Html.BeginForm("SuaSanPham", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="body-title-admin">
            <input type="button" value="Sửa thông tin" class="title-change" id="button-themthongtin" />
            @*<input type="button" value="Thêm hình ảnh" class="title-change" id="button-themanh" />*@
        </div>
        <div class="body-content-admin" style="padding: 16px">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(x => x.SanPhamID)
            <div class="form-mode" id="form-thongtin">
                <div class="item">
                    <label for="">Tên sản phẩm</label>
                    @Html.TextBoxFor(x => x.SanPhamName, new { @class = "input", @placeholder = "Nhập tên sản phẩm...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.SanPhamName, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="" style="width:100%">Ảnh đại diện</label>
                    <img src="~/Content/assets/images/@Model.SanPhamImage" width="200" id="output"/>
                    @*<input type="hidden" name="SanPhamImage" value="@Model.SanPhamImage" />*@
                    <label for="ufile" style="cursor:pointer">
                        Chọn ảnh
                    </label>
                    <input type="file" name="SanPhamImage" id="ufile" onchange="uploadFile(event)" style="display:none" />
                    @Html.ValidationMessageFor(x => x.SanPhamImage, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Năm sản xuất</label>
                    @Html.TextBoxFor(x => x.SanPhamProducedYear, new { @class = "input", @placeholder = "Nhập năm sản xuất...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.SanPhamProducedYear, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    @Html.LabelFor(model => model.DanhMucID, "Danh mục", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.DropDownList("DanhMucID", null, htmlAttributes: new { @class = "input" })
                    @Html.ValidationMessageFor(model => model.DanhMucID, "", new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Thương hiệu</label>
                    @Html.DropDownList("ThuongHieuID", null, htmlAttributes: new { @class = "input" })
                    @Html.ValidationMessageFor(model => model.ThuongHieuID, "", new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Số lượng</label>
                    @Html.TextBoxFor(x => x.SanPhamQuantity, new { @class = "input", @placeholder = "Nhập số lượng...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.SanPhamQuantity, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Đơn giá</label>
                    @Html.TextBoxFor(x => x.SanPhamUnitPrice, new { @class = "input", @placeholder = "Nhập đơn giá...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.SanPhamUnitPrice, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Trạng thái</label>
                    @{
                        var a = "Kích hoạt";
                        var b = "Vô hiệu";
                        var c = "";
                        if (Model.SanPhamStatus == 1)
                        {
                            c = a;
                        }
                        else
                        {
                            c = b;
                        }
                        IEnumerable<string> status = new List<string> { a, b };
                    }
                    @Html.DropDownList("status", new SelectList(status, c), new { @class = "input" })
                </div>
                <div class="item">
                    <label for="" style="width:100%">Mô tả</label>
                    @Html.TextAreaFor(x => x.SanPhamDescription, new { @class = "text-area", @placeholder = "Nhập mô tả...", @id = "text-area-description" })
                    @Html.ValidationMessageFor(x => x.SanPhamDescription, null, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="body-footer" style="justify-content: end; column-gap: 16px;padding-right: 30px">
            <a href="/admin/SanPham/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
            <button class="button-pop-up-footer" type="submit">Xác nhận</button>
        </div>
    }
</div>
<script>
    $(document).ready(function () {
        CKEDITOR.replace('text-area-description', {
            customConfig: '/content/ckeditor/config.js',
            extraAllowedContent: 'span',
        });
    });
</script>
<script>
    var uploadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0])
    }
</script>
@Scripts.Render("~/bundles/jqueryval")