LinhDGT_Electronic/LinhDGT_Electronic/Models/EF/ThuongHieu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LinhDGT_Electronic.Models.EF
{
    [Table("thuonghieu")]
    public class ThuongHieu
    {
        public ThuongHieu()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ThuongHieuID { get; set; }
        [Required(ErrorMessage = "Tên thương hiệu không được rỗng!")]
        public string ThuongHieuName { get; set; }

        [System.Web.Mvc.AllowHtml]
        public string ThuongHieuDescription { get; set; }
        public int ThuongHieuStatus { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set;}
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Controllers/ThuongHieuController.cs
using LinhDGT_Electronic.Models.EF;
using LinhDGT_Electronic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Web.Helpers;

namespace LinhDGT_Electronic.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ThuongHieuController : Controller
    {
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Admin/ThuongHieu
        public ActionResult Index(int? page, string timkiem, string boloc, string sapxep)
        {
            ViewBag.sapxep = sapxep;
            ViewBag.sapxeptheoten = String.IsNullOrEmpty(sapxep) ? "ten_desc" : "";
            IEnumerable<ThuongHieu> items = _dbContext.ThuongHieus.OrderByDescending(x => x.ThuongHieuID);
            var pagesize = 10;
            if (timkiem != null)
            {
                page = 1;
            }
            else
            {
                timkiem = boloc;
            }
            ViewBag.boloc = boloc;
            switch (sapxep)
            {
                case "ten_desc":
                    items = items.OrderByDescending(p => p.ThuongHieuName);
                    break;
                default:
                    items = items.OrderBy(p => p.ThuongHieuName);
                    break;
            }
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(timkiem))
            {
                items = items.Where(x => x.ThuongHieuName.ToLower().Contains(timkiem));
            }
            var pagenumber = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pagenumber, pagesize);
            ViewBag.page = page;
            ViewBag.pagesize = pagesize;
            return View(items);
        }
        [HttpGet]
        public ActionResult ThemThuongHieu()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ThemThuongHieu(FormCollection f, ThuongHieu model)
        {

            if (ModelState.IsValid)
            {
                if (f["status"] == "Kích hoạt")
                    model.ThuongHieuStatus = 1;
                else
                    model.ThuongHieuStatus = 2;
                _dbContext.ThuongHieus.Add(model);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult SuaThuongHieu(int id)
        {
            var item = _dbContext.ThuongHieus.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SuaThuongHieu(FormCollection f, ThuongHieu model)
        {

            if (ModelState.IsValid)
            {
                if (f["status"] == "Kích hoạt")
                    model.ThuongHieuStatus = 1;
                else model.ThuongHieuStatus = 2;
                _dbContext.ThuongHieus.Attach(model);
                _dbContext.Entry(model).Property(x => x.ThuongHieuName).IsModified = true;
                _dbContext.Entry(model).Property(x => x.ThuongHieuStatus).IsModified = true;
                _dbContext.Entry(model).Property(x => x.ThuongHieuDescription).IsModified = true;
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult XoaThuongHieu(int id)
        {
            var item = _dbContext.ThuongHieus.Find(id);
            if (item != null)
            {
                _dbContext.ThuongHieus.Remove(item);
                _dbContext.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/ThuongHieu/Index.cshtml
@model PagedList.PagedList<LinhDGT_Electronic.Models.EF.ThuongHieu>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Quản lý thương hiệu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="body">
    <div class="body-title-admin">
        <div class="title">Danh sách thương hiệu</div>
        @using (Html.BeginForm())
        {
            <div class="page-search">
                @Html.TextBox("timkiem", ViewBag.boloc as string, new { @class = "input-search", @placeholder = "Nhập từ khoá để tìm kiếm" })
                <input type="submit" class="button-search" value="Tìm kiếm" />
            </div>
        }
        <a class="button-admin-control-create" href="/admin/ThuongHieu/themThuongHieu">Thêm mới</a>
        <button class="button-admin-control-delete"><i class="fa-solid fa-trash"></i></button>
    </div>
    <div class="body-content-admin">
        <div class="table-content">

            <table class="table-body">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>@Html.ActionLink("Tên thương hiệu", "Index", new { sapxep = ViewBag.sapxeptheoten, boloc = ViewBag.boloc })</th>
                        <th>Trạng thái</th>
                        <th colspan="2">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.page - 1) * ViewBag.pagesize + 1);
                        var status = "";

                        foreach (var item in Model)
                        {
                            if (item.ThuongHieuStatus == 1)
                            {
                                status = "Kích hoạt";
                            }
                            else if (item.ThuongHieuStatus == 2)
                            {
                                status = "Vô hiệu";
                            }
                            <tr id="row_thuonghieu_@item.ThuongHieuID">
                                <td>@i</td>
                                <td>@item.ThuongHieuName</td>
                                <td>@status</td>
                                <td style="display:flex; justify-content:center;border:unset"><a class="button-admin-control-edit" href="/admin/thuonghieu/suathuonghieu/@item.ThuongHieuID"><i class="fa-solid fa-pen"></i></a></td>
                                <td style="display:flex; justify-content:center;border:unset"><a data-id="@item.ThuongHieuID" class="button-admin-control-edit button-delete-thuonghieu-by-id" style="background-color:red;border-color:red"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            i++;
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="7">Không có bản ghi</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="body-footer">
        <div style="padding-left:16px;box-sizing:border-box">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sapxep = ViewBag.sapxep, boloc = ViewBag.boloc }))</div>
        <span style="padding-right: 16px;box-sizing:border-box">Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</span>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('body').on('click', '.button-delete-thuonghieu-by-id', function () {
            var id = $(this).data("id");
            var conf = confirm('Xoá bản ghi?');
            if (conf === true) {
                $.ajax({
                    url: '/admin/thuonghieu/xoathuonghieu',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            $('#row_thuonghieu_' + id).remove();
                            location.reload();
                            alert('Đã xoá!');
                        }
                    }
                });
               
            }
        });
    });
</script>

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/ThuongHieu/SuaThuongHieu.cshtml
@model LinhDGT_Electronic.Models.EF.ThuongHieu
@{
    ViewBag.Title = "Sửa thương hiệu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Sửa thương hiệu</div>
    </div>
    <div class="body-content-admin" style="padding: 16px">
        @using (Html.BeginForm("SuaThuongHieu", "ThuongHieu", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(x => x.ThuongHieuID)
            <div class="form-mode">
                <div class="item">
                    <label for="">Tên thương hiệu</label>
                    @Html.TextBoxFor(x => x.ThuongHieuName, new { @class = "input", @placeholder = "Nhập tên thương hiệu...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.ThuongHieuName, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Trạng thái</label>
                    @{
                        var a = "Kích hoạt";
                        var b = "Vô hiệu";
                        var c = "";
                        if (Model.ThuongHieuStatus == 1)
                        {
                            c = a;
                        }
                        else
                        {
                            c = b;
                        }
                        IEnumerable<string> status = new List<string> { a,b };
                    }
                    @Html.DropDownList("status", new SelectList(status, c), new { @class = "input" })
                </div>
                <div class="item">
                    <label for="" style="width:100%">Mô tả</label>
                    @Html.TextAreaFor(x => x.ThuongHieuDescription, new { @class = "text-area", @placeholder = "Nhập mô tả...",@id = "text-area-description" })
                    @Html.ValidationMessageFor(x => x.ThuongHieuDescription, null, new { @class = "text-danger" })
                </div>
                <div class="item" style="justify-content: end; column-gap: 16px;">
                    <a href="/admin/ThuongHieu/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
                    <button class="button-pop-up-footer" type="submit">Xác nhận</button>
                </div>
            </div>
        }
    </div>
    <div class="body-footer">

    </div>
</div>
<script>
        $(document).ready(function () {
            CKEDITOR.replace('text-area-description', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
</script>

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/ThuongHieu/ThemThuongHieu.cshtml
@model LinhDGT_Electronic.Models.EF.ThuongHieu
@{
    ViewBag.Title = "Thêm thương hiệu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Thêm mới thương hiệu</div>
    </div>
    <div class="body-content-admin" style="padding: 16px">
        @using (Html.BeginForm("ThemThuongHieu", "ThuongHieu", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-mode">
                <div class="item">
                    <label for="">Tên thương hiệu</label>
                    @Html.TextBoxFor(x => x.ThuongHieuName, new { @class = "input", @placeholder = "Nhập tên thương hiệu...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.ThuongHieuName, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Trạng thái</label>
                    @{
                        IEnumerable<string> status = new List<string> { "Kích hoạt", "Vô hiệu" };
                    }
                    @Html.DropDownList("status", new SelectList(status, status.FirstOrDefault()), new { @class = "input" })
                </div>
                <div class="item">
                    <label for="" style="width:100%">Mô tả</label>
                    @Html.TextAreaFor(x => x.ThuongHieuDescription, new { @class = "text-area", @placeholder = "Nhập mô tả...", @id = "text-area-description",@name = "ThuongHieuDescription" })
                    @Html.ValidationMessageFor(x => x.ThuongHieuDescription, null, new { @class = "text-danger" })
                </div>
                <div class="item" style="justify-content: end; column-gap: 16px;">
                    <a href="/admin/ThuongHieu/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
                    <button class="button-pop-up-footer" type="submit">Xác nhận</button>
                </div>
            </div>
        }
    </div>
    <div class="body-footer">

    </div>
</div>

<script>
        $(document).ready(function () {
            CKEDITOR.replace('text-area-description', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
</script>