LinhDGT_Electronic/LinhDGT_Electronic/Models/EF/DanhMuc.cs
using LinhDGT_Electronic.Migrations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace LinhDGT_Electronic.Models.EF
{
    [Table("danhmuc")]
    public class DanhMuc
    {
        public DanhMuc()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DanhMucID { get; set; }
        [Required(ErrorMessage = "Tên danh mục không được để trống!")]
        public string DanhMucName { get; set; }
        
        [AllowHtml]
        public string DanhMucDescription { get; set; }
        public int DanhMucStatus { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Controllers/DanhMucController.cs
using LinhDGT_Electronic.Models;
using LinhDGT_Electronic.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinhDGT_Electronic.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DanhMucController : Controller
    {
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Admin/DanhMuc

        /// <summary>
        /// Màn hình quản lý danh mục kết hợp tìm kiếm, phân trang, sắp xếp
        /// </summary>
        /// <param name="page"></param>
        /// <param name="timkiem"></param>
        /// <param name="boloc"></param>
        /// <param name="sapxep"></param>
        /// <returns></returns>
        public ActionResult Index(int? page, string timkiem, string boloc, string sapxep)
        {
            ViewBag.sapxep = sapxep;
            ViewBag.sapxeptheoten = String.IsNullOrEmpty(sapxep) ? "ten_desc" : "";
            IEnumerable<DanhMuc> items = _dbContext.DanhMucs.OrderByDescending(x=>x.DanhMucID);
            var pagesize = 10;
            if (timkiem != null)
            {
                page = 1;
            }
            else
            {
                timkiem = boloc;
            }
            ViewBag.boloc = boloc;
           
            switch (sapxep)
            {
                case "ten_desc":
                    items = items.OrderByDescending(p => p.DanhMucName);
                    break;
                default:
                    items = items.OrderBy(p => p.DanhMucName);
                    break;
            }
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(timkiem))
            {
                items = items.Where(x => x.DanhMucName.ToLower().Contains(timkiem));
            }
            var pagenumber = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pagenumber, pagesize);
            ViewBag.page = page;
            ViewBag.pagesize = pagesize;
            return View(items);
        }

        /// <summary>
        /// Màn hình thêm danh mục
        /// </summary>
        /// <returns></returns>
        public ActionResult ThemDanhMuc()
        {

            return View();
        }
        /// <summary>
        /// Chức năng thêm danh mục
        /// </summary>
        /// <param name="f"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ThemDanhMuc(FormCollection f, DanhMuc model)
        {

            if (ModelState.IsValid)
            {
                if (f["status"] == "Kích hoạt")
                    model.DanhMucStatus = 1;
                else 
                    model.DanhMucStatus = 2;
                _dbContext.DanhMucs.Add(model);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Màn hình sửa danh mục
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SuaDanhMuc(int id) {
            var item = _dbContext.DanhMucs.Find(id);
            return View(item);
        }

        /// <summary>
        /// Chức năng sửa danh mục
        /// </summary>
        /// <param name="f"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SuaDanhMuc(FormCollection f, DanhMuc model)
        {

            if (ModelState.IsValid)
            {
                if (f["status"] == "Kích hoạt")
                    model.DanhMucStatus = 1;
                else model.DanhMucStatus = 2;
                _dbContext.DanhMucs.Attach(model);
                _dbContext.Entry(model).Property(x => x.DanhMucName).IsModified = true;
                _dbContext.Entry(model).Property(x => x.DanhMucStatus).IsModified = true;
                _dbContext.Entry(model).Property(x => x.DanhMucDescription).IsModified = true;
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        /// <summary>
        /// Chức năng xoá danh mục
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult XoaDanhMuc(int id)
        {
            var item = _dbContext.DanhMucs.Find(id);
            if (item != null)
            {
                _dbContext.DanhMucs.Remove(item);
                _dbContext.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false});
        }
    }
}

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/DanhMuc/Index.cshtml
@model PagedList.PagedList<LinhDGT_Electronic.Models.EF.DanhMuc>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Quản lý danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";


}
<div class="body">
    <div class="body-title-admin">
        <div class="title">Danh sách danh mục</div>
        @using (Html.BeginForm())
        {
            <div class="page-search">
                @Html.TextBox("timkiem", ViewBag.boloc as string, new { @class = "input-search", @placeholder = "Nhập từ khoá để tìm kiếm" })
                <input type="submit" class="button-search" value="Tìm kiếm" />
            </div>
        }

        <a class="button-admin-control-create" href="/admin/danhmuc/themdanhmuc">Thêm mới</a>
        <button class="button-admin-control-delete"><i class="fa-solid fa-trash"></i></button>
    </div>
    <div class="body-content-admin">
        <div class="table-content">

            <table class="table-body">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>@Html.ActionLink("Tên danh mục", "Index", new { sapxep = ViewBag.sapxeptheoten, boloc = ViewBag.boloc })</th>
                        <th>Trạng thái</th>
                        <th colspan="2">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.page - 1) * ViewBag.pagesize + 1);
                        var status = "";

                        foreach (var item in Model)
                        {
                            if (item.DanhMucStatus == 1)
                            {
                                status = "Kích hoạt";
                            }
                            else if (item.DanhMucStatus == 2)
                            {
                                status = "Vô hiệu";
                            }
                            <tr id="row_danhmuc_@item.DanhMucID">
                                <td>@i</td>
                                <td>@item.DanhMucName</td>
                                <td>@status</td>
                                <td style="display:flex; justify-content:center;border:unset"><a class="button-admin-control-edit" href="/admin/danhmuc/suadanhmuc/@item.DanhMucID"><i class="fa-solid fa-pen"></i></a></td>
                                <td style="display:flex; justify-content:center;border:unset"><a data-id="@item.DanhMucID" class="button-admin-control-edit button-delete-danhmuc-by-id" style="background-color:red;border-color:red"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            i++;
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="7">Không có bản ghi</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="body-footer">
        <div style="padding-left:16px;box-sizing:border-box">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sapxep = ViewBag.sapxep, boloc = ViewBag.boloc }))</div>
        <span style="padding-right: 16px;box-sizing:border-box">Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</span>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('body').on('click', '.button-delete-danhmuc-by-id', function () {
            var id = $(this).data("id");
            var conf = confirm('Xoá bản ghi?');
            if (conf === true) {
                $.ajax({
                    url: '/admin/danhmuc/xoadanhmuc',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            $('#row_danhmuc_' + id).remove();
                            location.reload();
                            alert('Đã xoá!');
                        }
                    }
                });
            }
        });

    });
</script>

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/DanhMuc/SuaDanhMuc.cshtml
@model LinhDGT_Electronic.Models.EF.DanhMuc
@{
    ViewBag.Title = "Sửa Danh Mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Sửa danh mục</div>
    </div>
    <div class="body-content-admin" style="padding:16px">
        @using (Html.BeginForm("SuaDanhMuc", "DanhMuc", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(x => x.DanhMucID)
            <div class="form-mode">
                <div class="item">
                    <label for="">Tên danh mục</label>
                    @Html.TextBoxFor(x => x.DanhMucName, new { @class = "input", @placeholder = "Nhập tên danh mục..." })
                    @Html.ValidationMessageFor(x => x.DanhMucName, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Trạng thái</label>
                    @{
                        var a = "Kích hoạt";
                        var b = "Vô hiệu";
                        var c = "";
                        if (Model.DanhMucStatus == 1)
                        {
                            c = a;
                        }
                        else
                        {
                            c = b;
                        }
                        IEnumerable<string> status = new List<string> { a, b };

                    }
                    @Html.DropDownList("status", new SelectList(status, c), new { @class = "input" })
                </div>
                <div class="item">
                    <label for="" style="width:100%">Mô tả</label>
                    @Html.TextAreaFor(x => x.DanhMucDescription, new { @class = "text-area", @placeholder = "Nhập mô tả...", @id = "text-area-description" })
                    @Html.ValidationMessageFor(x => x.DanhMucDescription, null, new { @class = "text-danger" })
                    
                </div>
                <div class="item" style="justify-content: end; column-gap: 16px;">
                    <a href="/admin/danhmuc/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
                    <button class="button-pop-up-footer" type="submit">Xác nhận</button>
                </div>
            </div>
        }
    </div>
    <div class="body-footer">

    </div>
</div>
<script>
        $(document).ready(function () {
            CKEDITOR.replace('text-area-description', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
</script>

LinhDGT_Electronic/LinhDGT_Electronic/Areas/Admin/Views/DanhMuc/ThemDanhMuc.cshtml
@model LinhDGT_Electronic.Models.EF.DanhMuc
@{
    ViewBag.Title = "Thêm Danh Mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="body">
    <div class="body-title-admin">
        <div class="title">Thêm mới danh mục</div>
    </div>
    <div class="body-content-admin" style="padding: 16px">
        @using (Html.BeginForm("ThemDanhMuc", "DanhMuc", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-mode">
                <div class="item">
                    <label for="">Tên danh mục</label>
                    @Html.TextBoxFor(x => x.DanhMucName, new { @class = "input", @placeholder = "Nhập tên danh mục...", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.DanhMucName, null, new { @style = "color:red" })
                </div>
                <div class="item">
                    <label for="">Trạng thái</label>
                    @{
                        IEnumerable<string> status = new List<string> { "Kích hoạt", "Vô hiệu" };
                    }
                    @Html.DropDownList("status", new SelectList(status, status.FirstOrDefault()), new { @class = "input" })
                </div>
                <div class="item">
                    <label for="" style="width:100%">Mô tả</label>
                    @Html.TextAreaFor(x => x.DanhMucDescription, new { @class = "text-area", @placeholder = "Nhập mô tả...", @id = "text-area-description" })
                    @Html.ValidationMessageFor(x => x.DanhMucDescription, null, new { @class = "text-danger" })
                </div>
                <div class="item" style="justify-content: end; column-gap: 16px;">
                    <a href="/admin/danhmuc/index" class="button-pop-up-footer" style="display:flex;justify-content:center;align-items:center">Quay lại</a>
                    <button class="button-pop-up-footer" type="submit">Xác nhận</button>
                </div>
            </div>
        }
    </div>
    <div class="body-footer">

    </div>
</div>
<script>
        $(document).ready(function () {
            CKEDITOR.replace('text-area-description', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
</script>